PORT: 3000
DATABASE: ENC:v1:kZJMSsSeWrTE0fZlqfz0kA==::27914f214c9619c750d1a27a3c24de58
HOST: localhost
USER: ENC:v1:Xg9V6gg34+TrGcr1+y4M4A==::3034397b0bc5606c98f70dcdd10c4714
PASSWORD: ENC:v1:zXWoPxczCcxvt7eJ9YCG5w==::60a172928c2d86d2da6f0b970bc8afc0
SMTP_USER: ENC:v1:iGcwLssNShUtiM/HvYnm/len4jTmknz0FBtC0tM/Ig8=::d987f64e07201aaff485e46e8f11ef9f
SMTP_PWD: ENC:v1:k7fSPfk9n/GN3eIlpvffRekzx2UOyLS7QDTPA9Hi13Y=::ca478a670cbdfdce5a58ef1458dd630c
SMTP_HOST:  smtp.office365.com
SMTP_PORT: 587
APP_CLIENTID: ENC:v1:BkJ5zlP3NibzI0ggw3YbFJgFBjbZmNe1CONJsJCTyYNVg6MoVKwcWxlcIeoKlCje::b45ddb8f6fc48911505be77f8448ffcf    
TENANTID: ENC:v1:+tyK6dUGyP+CcFC6j6YyxwIkThHLnEarXsBqhzrF/zzRRN24Pzy9kzyK2VDqNPkd::0a1ebd6a74770ec2ef806aa5be4e43d3        
SECRETVALUE: ENC:v1:UyUfOXw+LyMQt7Vg8JGTtYpROk8zt1C8M91r0Wo1S8FLq64Us736Ne0m2YIqKWmD::b18aa29aa92312bb8f7cc6034f5f1d12     
LISTID: ENC:v1:liWtNXO3VjKsrsFuoavL/myCT3YqnzJb088H055cbzdIBNAUnWBacmcIb4rmqgue::bc36c06b954ddaab07151bcafc1bef88
DAYS_TIME: 7
AIRTABLE_ACCESSTOKEN: ENC:v1:otm0I0tyWgJfcWdiyA/MR5lDrKjsZWUisIk8uqtAAkjepLKu7iI+lv6qI3IDyno+TGqyx3twWho+Jhfrbtb+373QSkjIU97PWD2jwibfxfWhhwxwgZE4fZPrtMieyrfW::c75790267eec21a126ef7342ecf95ce4
TABLE_ID: ENC:v1:qARn1K7X+tpwZKvUc0wl29paDef+CQy7oQRWNZ3VvCM=::569f1049a1fa4680c22bf551cdb86ec8
ENV: development